### ISSUE TITLE
Update the release on KVRAudio

### ISSUE THREAD

**Issue by aminya** [robianmcd/midi-shape-shifter#6]
@robianmcd I think you have access to this account. Please release a new version there (v1.0.11-beta).
https://www.kvraudio.com/developer/midi-shape-shifter

**Comment by robianmcd** [comment]
Wow thanks for reviving this project! I'm not sure how to build the installer for this anymore though. I used to use a free version of install shield but I think it doesn't exist anymore. I can take a look next week

**Comment by aminya** [comment]
You're welcome! This VST was a hidden gem in my DAW. That's why I decided to revive it! 

For uploading to KVR, we should probably use the installer I made for 1.0.11-beta:
https://github.com/robianmcd/midi-shape-shifter/releases/download/v1.0.11-beta/MidiShapeShifter-1.0.11-beta.zip

Regarding your question, running this "Rebuild Solution" command generates the installer. I changed the installer to the msi installer projects that come with Visual Studio.

![image](https://user-images.githubusercontent.com/16418197/171968167-b01c47a4-fd7c-4bd1-8436-265565f3c2b5.png)

If it doesn't build, you might need to install this:
https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects

**Comment by robianmcd** [comment]
I lost track of this. Thanks for the info! I updated the KVR release https://www.kvraudio.com/product/midi-shape-shifter-by-midi-shape-shifter/downloads

Sorry it took so long

**Comment by aminya** [comment]
Hey @robianmcd, I have updated the VST to v1.1.0. Could you please update the release on KVR?
https://github.com/robianmcd/midi-shape-shifter/releases/tag/v1.1.0

**Comment by robianmcd** [comment]
@aminya great thanks! I updated the KVR page
